name: 'Build package'
inputs:
  folder:
    required: true

runs:
  using: "composite"
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - uses: fregante/setup-git-user@v1
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
 
    - shell: bash 
      run: |
        cd ${{ inputs.folder }}
        npm install
        npm run build
        git add lib/*
        git diff-index --quiet HEAD || git commit -m 'Deploy ${{ inputs.folder }}!'
        git push

    - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
