name: 'Build package'
inputs:
  folder:
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash 
      run: |
        cd ${{ inputs.folder }}
        npm install
        npm run build
        git add lib/*
