name: 'Build package'
on:
  workflow_call:
    inputs:
      folder:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: fregante/setup-git-user@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
  
      - shell: bash 
        working-directory: ./${{ inputs.folder }}
        run: |
          npm install
          npm run build
          git add lib/*
          git diff-index --quiet HEAD || git commit -m 'Deploy ${{ inputs.folder }}!'
          git pull
          git push

      - uses: JS-DevTools/npm-publish@v1
        with:
          package: ./${{ inputs.folder }}/package.json
          token: ${{ secrets.NPM_TOKEN }}
