name: 'Publish package'
on:
  workflow_call:
    inputs:
      folder:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
  
      - shell: bash 
        working-directory: ./${{ inputs.folder }}
        run: |
          npm install

      - uses: JS-DevTools/npm-publish@v1
        with:
          package: ./${{ inputs.folder }}/package.json
          token: ${{ secrets.NPM_TOKEN }}
